import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/organisms/Header/Header";
import Hero from "../components/organisms/Hero/Hero";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Button from "../components/atoms/Button/Button";
import Icon from "../components/atoms/Icon/Icon";
import image_enterprice from "../assets/images/svg/Enterprise_Features.svg";
import image_financial from "../assets/images/svg/profession_financial.svg";
import rent_collection from "../assets/images/svg/rent_collection.svg";
import find_tenants from "../assets/images/svg/find_tenants.svg";
import reminders from "../assets/images/svg/reminders.svg";
import { shimmer, toBase64 } from "../helpers/component_helpers";
import Aside from "../components/organisms/aside/aside";
import Section from "../components/templates/Section";

const Home: NextPage = () => {
  return (
    <>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&amp;display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&amp;display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&amp;display=swap"
          rel="stylesheet"
        />
      </head>
   
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Hero />
        <Aside />
        {/* professional financial reporting */}

        <Section className="bg-light">
            <div className="row gx-5 align-items-center justify-content-center justify-content-lg-between">
              <div className="col-sm-8 col-md-6">
                <div className="px-5 px-sm-0">
                  <Image src={image_financial} />
                </div>
              </div>
              <div className="col-12 col-lg-5">
                <h2 className="display-5 lh-1 mb-4">
                  Professional financial reporting
                </h2>
                <p className="lead fw-normal text-muted mb-5 mb-lg-0">
                  Gain insight into your portfolio with access to 15+
                  customizable reports designed specifically for landlords.
                </p>
                <br />
                <p className="lead fw-normal text-muted mb-5 mb-lg-0">
                  Instantly generate professional reports, and share with your
                  accountant from any device. Landlord Studio helps tax
                  professionals keep their clients organized for tax season.
                </p>
              </div>
            </div>
       
        </Section>
        <Section className="bg-lighst">
          <div className="row gx-5 align-items-center justify-content-center justify-content-lg-between">
            <div className="col-12 col-lg-5">
              <h2 className="display-6 lh-1 mb-4">Make tax time easy</h2>
              <div className="d-flex gap-4 justify-content-start mb-4 mt-4">
                <div className="icon">
                  <Icon name="bi-app" color="blue" size={33}  />
                </div>
                <div>
                  <h4>Digital recipept</h4>
                  <p>
                    Go paperless with our Smart Scan technology, to instantly
                    digitize your receipts when you’re on-the-go.
                  </p>
                </div>
              </div>

              <div className="d-flex gap-4 justify-content-start mb-4 mt-4">
                <div className="icon">
                  <Icon name="bi-app" color="blue" size={33}  />
                </div>
                <div>
                  <h4>Digital recipept</h4>
                  <p>
                    Go paperless with our Smart Scan technology, to instantly
                    digitize your receipts when you’re on-the-go.
                  </p>
                </div>
              </div>
              <div className="row align-items-center gap-5 ">
                <Button
                  style={{ height: 60, width: "100%" }}
                  className="col btn btn-primary"
                >
                  TRY FOR FREE
                </Button>

                <div className="col">
                  <Link href="/login"> Discover rental accounting</Link>
                </div>
              </div>
            </div>
            <div className="col-sm-8 col-md-6">
              <div className="px-5 px-sm-0">
                <Image
                  blurDataURL={`data:image/svg+xml;base64,${toBase64(
                    shimmer(700, 475)
                  )}`}
                  placeholder="blur"
                  src={image_enterprice}
                />
              </div>
            </div>
          </div>
        </Section>
        <Section className="bg-light">
          <div className="row gx-5 align-items-center justify-content-center justify-content-lg-between">
            <div className="col-sm-8 col-md-6">
              <div className="px-5 px-sm-0">
                <Image src={rent_collection} />
              </div>
            </div>
            <div className="col-12 col-lg-5">
              <h2 className="display-5 lh-1 mb-4">
                Automated online rent collection
              </h2>
              <p className="lead fw-normal text-muted mb-5 mb-lg-0">
                Make late rent a problem of the past. Your tenants can easily
                and securely pay rent directly into your account, and even set
                up automated payments.
              </p>
              <br />
              <div className="row align-items-center gap-5 ">
                <Button
                  style={{ height: 60, width: "100%" }}
                  className="col btn btn-primary"
                >
                  TRY FOR FREE
                </Button>

                <div className="col">
                  <Link href="/login"> Discover rental accounting</Link>
                </div>
              </div>
            </div>
          </div>
        </Section>
        <Section className="bg-lights">
          <div className="row gx-5 align-items-center justify-content-center justify-content-lg-between">
            <div className="col-12 col-lg-5">
              <h2 className="display-5 lh-1 mb-4">Find the perfect tenants</h2>
              <p className="lead fw-normal text-muted mb-5 mb-lg-0">
                Make late rent a problem of the past. Your tenants can easily
                and securely pay rent directly into your account, and even set
                up automated payments.
              </p>
              <br />
              <div className="row align-items-center gap-5 ">
                <div className="col">
                  <Link href="/login"> Discover rental accounting</Link>
                </div>
              </div>
            </div>
            <div className="col-sm-8 col-md-6">
              <div className="px-5 px-sm-0">
                <Image src={find_tenants} />
              </div>
            </div>
          </div>
        </Section>

        <Section className="bg-light">
          <div className="row gx-5 align-items-center justify-content-center justify-content-lg-between">
            <div className="col-12 col-lg-4">
              <h2 className="display-s6 lh-1 mb-4">Make tax time easy</h2>
              <div className="d-flex gap-4 justify-content-start mb-4 mt-4">
                <div className="icon">
                  <Icon  name="bi-app" color="blue" size={33}  />
                </div>
                <div>
                  <h5>Digital recipept</h5>
                  <p>
                    Go paperless with our Smart Scan technology, to instantly
                    digitize your receipts when you’re on-the-go.
                  </p>
                </div>
              </div>

              <div className="d-flex gap-4 justify-content-start mb-4 mt-4">
                <div className="icon">
                  <Icon name="bi-app" color="blue" size={33}   />
                </div>
                <div>
                  <h5>Digital recipept</h5>
                  <p>
                    Go paperless with our Smart Scan technology, to instantly
                    digitize your receipts when you’re on-the-go.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-sm-8 col-md-6 col-lg-4">
              <div
                style={{ transform: "scale(1.39)" }}
                className="px-5 px-sm-0"
              >
                <Image width={600} height={1000} src={reminders} />
              </div>
            </div>
            <div className="col-12 col-lg-4">
              <h2 className="displays-6 lh-1 mb-4">Make tax time easy</h2>
              <div className="d-flex gap-4 justify-content-start mb-4 mt-4 align-item">
                <div className="icon">
                  <Icon name="bi-app" size={33} color="blue" />
                </div>
                <div>
                  <h5>Digital recipept</h5>
                  <p>
                    Go paperless with our Smart Scan technology, to instantly
                    digitize your receipts when you’re on-the-go.
                  </p>
                </div>
              </div>

              <div className="d-flex gap-4 justify-content-start mb-4 mt-4">
                <div className="icon">
                  <Icon  name="bi-app" color="blue" size={33}  />
                </div>
                <div>
                  <h5>Digital recipept</h5>
                  <p>
                    Go paperless with our Smart Scan technology, to instantly
                    digitize your receipts when you’re on-the-go.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </Section>
      </div>
    </div>
    </>
  );
};

export default Home;
