import Authlayout from "../../components/templates/Authlayout";
import Head from "next/head";
import Section from "../../components/templates/Section";
import Button from "components/atoms/Button/Button";
import Container from "components/templates/container";
import Card from "components/templates/card";
import Accordion from "components/templates/layouts/accordion";
import Row from "components/templates/layouts/Row";

const Dashboard = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Authlayout>
        <Container>
          <Accordion header="Filters"></Accordion>
          <div className="row">
            {[1, 2, 3, 4].map((card, i) => (
              <div key={i} className="col-lg-3 col-md-6 mb-4">
                <Card>
                  <Card.Title>Card title</Card.Title>
                  <Card.Text>
                    Some quick example text to build on the card title and make
                    up the bulk of the card's content.
                  </Card.Text>
                </Card>
              </div>
            ))}
          </div>
          <div className="row">
            <div className="col-4">
              <Card>
                <Card.Title>Property portfolio</Card.Title>
              </Card>
            </div>
            <div className="col-4">
              <Card>
                <Card.Title>Occupation</Card.Title>
              </Card>
            </div>
            <div className="col-4">
              <Card>
                <Card.Title>Rental collection</Card.Title>
              </Card>
            </div>
          </div>
          <div className="row mt-3">
            <div className="col-lg-12">
              <Card></Card>
            </div>
          </div>
        </Container>
      </Authlayout>
    </>
  );
};

export default Dashboard;
