import Authlayout from "../../components/templates/Authlayout";
import Head from "next/head";
import Section from "../../components/templates/Section";
import Button from "components/atoms/Button/Button";
import Container from "components/templates/container";
import Card from "components/templates/card";
import Accordion from "components/templates/layouts/accordion";
import Row from "components/templates/layouts/Row";
import Icon from 'components/atoms/Icon/Icon'
import Modal from 'components/common/Modal'
import React from 'react'

const Dashboard = () => {
  const [showModal,SetShowModal] = React.useState(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Authlayout>
        <Container>
          <Accordion header="Filters">
            <button onClick={()=>SetShowModal(true)} className="btn btn-primary">Open</button>
          </Accordion>
          <div className="row">
            {[1, 2, 3, 4].map((card, i) => (
              <div key={i} className="col-lg-3 col-md-6 mb-4">
                <Card  backgroundImg border>
                  <div className="position-absolute">
                  <Icon name="bi-cash" />
                  </div>
                  <div className="d-flex flex-column mt-5">
                    <Card.Text>
                    GBP 0.00
                    </Card.Text>
                    <small>
                    0 overdue 
                    </small>
                  </div>

                </Card>
              </div>
            ))}
          </div>
          <div className="row">
            <div className="col-4">
              <Card>
                <Card.Title>Property portfolio</Card.Title>
              </Card>
            </div>
            <div className="col-4">
              <Card>
                <Card.Title>Occupation</Card.Title>
              </Card>
            </div>
            <div className="col-4">
              <Card>
                <Card.Title>Rental collection</Card.Title>
              </Card>
            </div>
          </div>
          <div className="row mt-3">
            <div className="col-lg-12">
              <Card></Card>
            </div>
          </div>
        </Container>
      </Authlayout>
    </>
  );
};

export default Dashboard;
