import Authlayout from "../../components/templates/Authlayout";
import Head from "next/head";
import Section from '../../components/templates/Section'

const Dashboard = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
          
  
        {/* <Section>
            sss
        </Section> */}

   
     <Authlayout>
            <button className="btn btn-primary">
                <p>
                wwwwwwwwwexportwww  hhhh 
                </p>
            </button>
      </Authlayout>
  
    </>
  );
};

export default Dashboard;
